package Modelos;
// Generated 5/11/2015 08:28:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuarios;
     private String nombres;
     private String apellidos;
     private long numeroDocumento;
     private long telefono;
     private String correo;
     private String direccion;
     private String tipoUsuario;
     private String user;
     private String pass;
     private String estado;
     private Set seguimientoses = new HashSet(0);
     private Set contratoses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombres, String apellidos, long numeroDocumento, long telefono, String correo, String direccion, String tipoUsuario, String estado) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numeroDocumento = numeroDocumento;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
        this.tipoUsuario = tipoUsuario;
        this.estado = estado;
    }
    public Usuario(String nombres, String apellidos, long numeroDocumento, long telefono, String correo, String direccion, String tipoUsuario, String user, String pass, String estado, Set seguimientoses, Set contratoses) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numeroDocumento = numeroDocumento;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
       this.tipoUsuario = tipoUsuario;
       this.user = user;
       this.pass = pass;
       this.estado = estado;
       this.seguimientoses = seguimientoses;
       this.contratoses = contratoses;
    }

    public Usuario(Integer idUsuarios, String nombres, String apellidos, long numeroDocumento, long telefono, String correo, String direccion, String tipoUsuario) {
        this.idUsuarios = idUsuarios;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numeroDocumento = numeroDocumento;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
        this.tipoUsuario = tipoUsuario;
    }
    
    
   
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public long getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(long numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSeguimientoses() {
        return this.seguimientoses;
    }
    
    public void setSeguimientoses(Set seguimientoses) {
        this.seguimientoses = seguimientoses;
    }
    public Set getContratoses() {
        return this.contratoses;
    }
    
    public void setContratoses(Set contratoses) {
        this.contratoses = contratoses;
    }




}


